#!/bin/bash
#
# How to run
# cd $FlyWithLua_REPO
# ./build-Hello-World-SDK-4_win_mac_lin_WithCmake_OnLinux

rm -r HelloWorldSdk4/win_x64/*.xpl
rm -r HelloWorldSdk4/lin_x64/*.xpl
rm -r HelloWorldSdk4/mac_x64/*.xpl


# Windows build

 rm -r build/*
 cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-mingw-w64-x86-64.cmake
 cmake --build ./build -v
 cp ./build/win.xpl ./HelloWorldSdk4/win_x64/HelloWorldSdk4.xpl


# Linux build

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build ./build -v
cp ./build/lin.xpl ./HelloWorldSdk4/lin_x64/HelloWorldSdk4.xpl


# Mac build

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-ubuntu-osxcross-x86_64-11.3.cmake
cmake --build ./build -v
cp ./build/mac.xpl ./HelloWorldSdk4/mac_x64/HelloWorldSdk4.xpl

exec $SHELL
#

